#!/bin/sh
RED="\033[1;31m"
linter_exit_code=1
git_exit_code=1
files_to_lint=$(git diff --cached --diff-filter=d --name-only | grep '.ts$\|.tsx$')
yarn prettier-eslint $files_to_lint --write
linter_exit_code=$?
if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ prettier-eslint failed)${NC}"
  exit 1
else
  echo "${GREEN} ✔ prettier-eslint succeeded${NC}"
  #git add is broken, but this works?
  git update-index $files_to_lint --verbose
  git_exit_code=$?
fi
if [ $git_exit_code -ne 0 ]
then
  echo "${RED} ❌ git add failed)${NC}"
  exit 1
else
  echo "${GREEN} ✔ git add succeeded${NC}"
fi

exit 0